### ISSUE TITLE
仓库的菜单

### ISSUE THREAD

**Issue by wujixian** [maioria/aitake-saas#1]
你好 大佬  仓库相关的菜单数据给出的sql文件好像没有  你那边还有吗

**Comment by maioria** [comment]
已经补充sql

**Comment by wujixian** [comment]
感觉大佬能回复  好像还缺字典数据，大佬麻烦再发一下吧  谢谢  谢谢
![image](https://github.com/maioria/aitake-saas/assets/11608170/57f1bf9d-295a-4378-bf4d-45d5b053f137)
![image](https://github.com/maioria/aitake-saas/assets/11608170/31172355-6ba1-47e0-aa9a-b5f683cd47f8)

**Comment by maioria** [comment]
已经补充上了

**Comment by wujixian** [comment]
真速度 大佬  膜拜

**Comment by wujixian** [comment]
大佬 全了 谢谢大佬
